### ISSUE TITLE
--wait option raises exception in globus SDK

### ISSUE THREAD

**Issue by brockpalen** [brockpalen/archivetar#17]
The `--wait` option is working as expected but is causing an exception at the end of the run.  

Example Command:

` archivetar --tar-size 20G --prefix my-prefix --destination-dir /nfs/dataden/flux-support-dd/brockp/test/ --wait  --rm-at-files`

```
Traceback (most recent call last):
  File "archivetar", line 21, in <module>
  File "archivetar/__init__.py", line 500, in main
  File "GlobusTransfer/__init__.py", line 119, in task_wait
  File "globus_sdk/services/transfer/client.py", line 1545, in task_wait
  File "globus_sdk/services/transfer/client.py", line 1427, in get_task
  File "globus_sdk/client.py", line 136, in get
  File "globus_sdk/client.py", line 298, in request
globus_sdk.services.transfer.errors.TransferAPIError: ('GET', 'https://transfer.api.globus.org/v0.10/task/None', 'Bearer', 400, 'BadRequest', "Invalid value for path arg 'task_id' of type 'string_uuid'", '6ETRKfyiN')
[114358] Failed to execute script 'archivetar' due to unhandled exception!

```

**Comment by brockpalen** [comment]
Line 500 calls `globus.task_wait(large_taskid)` which is only a valid taskid if we use the `--size` option to create a list of large and small files.  This could be fixed by ehter checking that `large_task not None`  or `if args.wait and args.size:`
