### ISSUE TITLE
ERROR:root:Issue during tar process killing

### ISSUE THREAD

**Issue by brockpalen** [brockpalen/archivetar#22]
```
 archivetar --prefix my-archive -v -v --tar-verbose

INFO:root:Complete my-archive-1.tar Size: 110.6 GB
DEBUG:root:Return code from tar my-archive-3.tar is 0
DEBUG:root:Return code from tar my-archive-2.tar is 0
DEBUG:root:Return code from tar my-archive-1.tar is 0
ERROR:root:Issue during tar process killing
Traceback (most recent call last):
  File "archivetar", line 21, in <module>
  File "archivetar/__init__.py", line 530, in main
  File "archivetar/__init__.py", line 526, in main
TypeError: exceptions must derive from BaseException
[1350036] Failed to execute script 'archivetar' due to unhandled exception!
```

**Comment by brockpalen** [comment]
This was fixed in  620f800384e
